// Canonical keys => possible GLB node names
export const ROOM_PARTS = {
  cube: ['Cube', 'cube'],
  aquarium: ['Aquarium', 'aquarium', 'FishTank', 'fish_tank'],
  computer: ['Computer', 'computer', 'PC', 'pc'] ,
  screen: ['Screen', 'screen', 'Monitor_Screen'],
  clock: ['Clock', 'clock'],
  shelves: ['Shelves', 'shelves', 'Shelf', 'shelf'],
  floor_items: ['Floor_Items', 'floor_items', 'FloorItems'],
  desks: ['Desks', 'desks', 'Desk', 'desk', 'Table', 'table'],
  table_stuff: ['Table_Stuff', 'table_stuff', 'TableStuff'],
  mini_floor: ['Mini_Floor', 'mini_floor'],
  chair: ['Chair', 'chair'],
  fish: ['Fish', 'fish'],
  body: ['Body', 'body', 'Room', 'room'],
  // Mini platform / pathway pieces (names vary by GLB version)
  mailbox: ['Mailbox', 'mailbox'],
  lamp: ['Lamp', 'lamp'],
  floor_first: ['FloorFirst', 'floorfirst', 'Floor_First', 'floor_first'],
  floor_second: ['FloorSecond', 'floorsecond', 'Floor_Second', 'floor_second'],
  floor_third: ['FloorThird', 'floorthird', 'Floor_Third', 'floor_third'],
  dirt: ['Dirt', 'dirt'],
  flower1: ['Flower1', 'flower1', 'Flower_1'],
  flower2: ['Flower2', 'flower2', 'Flower_2'],
};
